### ISSUE TITLE
V3.1 - going from minimzed to full size and back to minimize changes the location of the icon. 

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#11]
when going from minimized to full size and back to minimized changes the previous location of the minimize icon

**Comment by AndyPiddock** [comment]
Same answer as #12 
At the moment on closing Seth it will remember the top left position for next start up and as at the moment Seth can only be closed in the full open mode if you have chosen to open Seth minimized then this minimized opening will be from the full open position, so you need to make sure that Seth Top Left is where you want it to be opened minimized.. This was done so that I could get an open as minimized version out very quickly.
V3.2 will have the option to shutdown from the minimized state which means that Set will save two positions for startup. One for minimized and one for full.

**Comment by AndyPiddock** [comment]
Included in V3.2 release.
