### ISSUE TITLE
V3.1 - still does not save the location of the minimized icon

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#12]
After a restart the minimzed icon has lost its previous location.

**Comment by AndyPiddock** [comment]
At the moment on closing Seth it will remember the top left position for next start up and as at the moment Seth can only be closed in the full open mode if you have chosen to open Seth minimized then this minimized opening will be from the full open position, so you need to make sure that Seth Top Left is where you want it to be opened minimized.. This was done so that I could get an open as minimized version out very quickly.
V3.2 will have the option to shutdown from the minimized state which means that Set will save two positions for startup. One for minimized and one for full.

**Comment by AndyPiddock** [comment]
This now for V3.2

![explorer_2019-02-25_16-08-35](https://user-images.githubusercontent.com/37116306/53346594-9ea2a100-3917-11e9-8094-bd4ff3ac2d7f.png)

**Comment by AndyPiddock** [comment]
Included in V3.2 release.
